#!/usr/bin/env python3
"""Dry-run-first onboarding for Adaptative Living Library.

Local only: no LLM calls, no network, no global Hermes config edits, no active
memory writes, and no gateway restarts.
"""
from __future__ import annotations

import argparse
import re
import shutil
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEXT_SUFFIXES = {'.md', '.txt', '.json', '.jsonl', '.yaml', '.yml', '.csv', '.log'}
SKIP_PARTS = {'.git', '__pycache__', '.pytest_cache', 'node_modules', '.venv', 'venv', 'backups'}
STOP_WORDS = "the a an and or of in to for with without about how what why when where this that these those is are be i you me my our your from on into de la el los las y o que para con sin como una uno unas unos por del al en un con as at it its we they them he she his her their not no yes true false null"
STOP = set(STOP_WORDS.split())
ROLE_ORDER = ['librarian', 'scout', 'architect', 'oracle']
ROLE_LABELS = {
    'librarian': 'Librarian',
    'scout': 'Scout',
    'architect': 'Architect',
    'oracle': 'Oracle',
}


def tokens(text: str) -> list[str]:
    return [w for w in re.findall(r'[a-zA-Z][a-zA-Z0-9_-]{2,}', text.lower()) if w not in STOP and not w.startswith('http')]


def prompt(default: str, question: str, *, non_interactive: bool) -> str:
    if non_interactive:
        return default
    raw = input(f'{question} [{default}]: ').strip()
    return raw or default


def discover_default_sources(target: Path) -> tuple[list[Path], list[Path]]:
    session_candidates = [target / 'sessions', target / 'session_logs', target / 'logs' / 'sessions']
    memory_candidates = [target / 'memory', target / 'memories', target / 'mnemosyne', target / 'stash', target / 'libraries']
    return ([p for p in session_candidates if p.exists()], [p for p in memory_candidates if p.exists()])


def iter_text_files(paths: list[Path], *, max_files: int):
    seen = 0
    for base in paths:
        base = base.expanduser().resolve()
        if not base.exists():
            continue
        files = [base] if base.is_file() else base.rglob('*')
        for p in files:
            if seen >= max_files:
                return
            if not p.is_file():
                continue
            if any(part in SKIP_PARTS for part in p.parts):
                continue
            if p.suffix.lower() not in TEXT_SUFFIXES:
                continue
            seen += 1
            yield p


def scan_sources(session_sources: list[Path], memory_sources: list[Path], *, max_files: int, max_bytes: int):
    counter: Counter[str] = Counter()
    examples: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for kind, sources in [('session', session_sources), ('memory', memory_sources)]:
        for path in iter_text_files(sources, max_files=max_files):
            try:
                text = path.read_text(encoding='utf-8', errors='ignore')[:max_bytes]
            except OSError:
                continue
            toks = tokens(text)
            counter.update(toks)
            top = [w for w, _ in Counter(toks).most_common(8)]
            excerpt = re.sub(r'\s+', ' ', text[:500]).strip()
            for term in top[:5]:
                if len(examples[term]) < 3:
                    examples[term].append((f'{kind}:{path}', excerpt[:280]))
    return counter, examples


def yaml_list(items: list[str], indent: int = 2) -> str:
    pad = ' ' * indent
    if not items:
        return pad + '[]\n'
    return ''.join(f'{pad}- {item}\n' for item in items)


def write(path: Path, text: str, *, dry_run: bool):
    print(f"{'DRY write' if dry_run else 'write'} {path}")
    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding='utf-8')


def render_profile(role: str, provider: str, model: str, target: Path, library_name: str) -> str:
    label = ROLE_LABELS[role]
    return f'''model:\n  provider: {provider}\n  default: {model}\nagent:\n  reasoning_effort: low\n  system_prompt: |\n    # {role}\n    You are {label}. Operate as part of the Adaptative Living Library.\n\n    Canonical path: {target}/libraries/{library_name}/\n    Before answering non-trivial questions, run or approximate:\n    python3 {target}/libraries/{library_name}/scripts/library_preflight.py "<query>" --limit 8\n\n    Respect safety gates: no crons, gateway restarts, model/provider changes, credentials, active memory writes, or global config edits without explicit approval.\nprofile:\n  description: {label} profile generated by Adaptative Living Library onboarding. Ready to bind to Telegram/Discord/CLI after operator review.\n'''


def create_obsidian_link(vault: Path, library: Path, *, dry_run: bool):
    vault = vault.expanduser().resolve()
    link = vault / 'Adaptative Living Library'
    if dry_run:
        print(f'DRY link Obsidian vault {link} -> {library}')
        return str(link)
    vault.mkdir(parents=True, exist_ok=True)
    if link.exists() or link.is_symlink():
        print(f'obsidian link exists: {link}')
        return str(link)
    try:
        link.symlink_to(library, target_is_directory=True)
        print(f'linked Obsidian vault {link} -> {library}')
    except OSError as exc:
        fallback = vault / 'ADAPTATIVE_LIVING_LIBRARY_LINK.md'
        fallback.write_text(f'''# Adaptative Living Library link\n\nAutomatic symlink failed: `{exc}`\n\nOpen this folder manually as an Obsidian vault or link/copy:\n\n```text\n{library}\n```\n''', encoding='utf-8')
        print(f'symlink failed; wrote {fallback}')
        return str(fallback)
    return str(link)


def main() -> int:
    ap = argparse.ArgumentParser()
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument('--dry-run', action='store_true')
    mode.add_argument('--apply', action='store_true')
    ap.add_argument('--target', default=str(Path.home() / '.hermes'))
    ap.add_argument('--library-name', default='adaptative-living-library')
    ap.add_argument('--operator-name', default='Operator')
    ap.add_argument('--provider', default='openrouter')
    ap.add_argument('--main-model', default='anthropic/claude-sonnet-4')
    ap.add_argument('--librarian-model')
    ap.add_argument('--scout-model')
    ap.add_argument('--architect-model')
    ap.add_argument('--oracle-model')
    ap.add_argument('--topic', action='append', default=[])
    ap.add_argument('--scan-existing', action='store_true')
    ap.add_argument('--session-source', action='append', default=[])
    ap.add_argument('--memory-source', action='append', default=[])
    ap.add_argument('--max-files', type=int, default=200)
    ap.add_argument('--max-bytes-per-file', type=int, default=12000)
    ap.add_argument('--obsidian-vault', default='')
    ap.add_argument('--non-interactive', action='store_true')
    args = ap.parse_args()

    dry_run = not args.apply or args.dry_run
    non_interactive = args.non_interactive or bool(args.topic) or dry_run
    target = Path(args.target).expanduser().resolve()
    library = target / 'libraries' / args.library_name

    provider = prompt(args.provider, 'Model provider', non_interactive=non_interactive)
    main_model = prompt(args.main_model, 'Default/main model', non_interactive=non_interactive)
    models = {
        'librarian': args.librarian_model or main_model,
        'scout': args.scout_model or main_model,
        'architect': args.architect_model or main_model,
        'oracle': args.oracle_model or main_model,
    }
    topics = list(args.topic)
    if not non_interactive:
        raw_topics = input('Scout topics, comma-separated: ').strip()
        if raw_topics:
            topics.extend([t.strip() for t in raw_topics.split(',') if t.strip()])

    session_sources = [Path(p).expanduser() for p in args.session_source]
    memory_sources = [Path(p).expanduser() for p in args.memory_source]
    if args.scan_existing:
        ds, dm = discover_default_sources(target)
        session_sources.extend(ds)
        memory_sources.extend(dm)

    counter, examples = scan_sources(session_sources, memory_sources, max_files=args.max_files, max_bytes=args.max_bytes_per_file) if (session_sources or memory_sources) else (Counter(), {})
    inferred = [w for w, _ in counter.most_common(20)]
    ts = datetime.now().strftime('%Y%m%d-%H%M%S')

    config = f'# Generated by scripts/onboard.py at {ts}\noperator_name: {args.operator_name}\nlibrary_name: {args.library_name}\nmodel_provider: {provider}\nmodels:\n'
    for role in ROLE_ORDER:
        config += f'  {role}: {models[role]}\n'
    config += 'topics:\n' + yaml_list(topics, 2)
    config += 'inferred_topics:\n' + yaml_list(inferred, 2)
    config += 'agents:\n'
    for role in ROLE_ORDER:
        config += f'  - profile: {role}\n    display_name: {ROLE_LABELS[role]}\n'

    raw = [f'# Initial onboarding discovery — {ts}', '', '## Explicit Scout topics']
    raw += [f'- {t}' for t in topics] or ['- None provided.']
    raw += ['', '## Inferred candidate topics from sessions/memory', '']
    raw += [f'- {t} ({counter[t]})' for t in inferred] or ['- No scan sources or no topics inferred.']
    raw += ['', '## Candidate raw evidence excerpts', '']
    for term in inferred[:12]:
        raw.append(f'### {term}')
        for src, excerpt in examples.get(term, [])[:3]:
            raw.append(f'- Source: `{src}`')
            raw.append(f'  Excerpt: {excerpt}')
        raw.append('')
    raw += ['## Safety note', 'This file is raw source material. Librarian must curate before anything becomes canon.']

    bindings = '# Generated by Adaptative Living Library onboarding\nprofiles:\n'
    for role in ROLE_ORDER:
        bindings += f'  - name: {role}\n    display_name: {ROLE_LABELS[role]}\n    model_provider: {provider}\n    model: {models[role]}\n    bind_status: ready_for_operator_review\n'

    guide = f'# Binding Guide — Adaptative Living Library\n\nGenerated: {ts}\n\nProfiles ready to bind:\n\n'
    for role in ROLE_ORDER:
        guide += f'- `{role}` — {ROLE_LABELS[role]} — model `{models[role]}` via `{provider}`\n'
    guide += '''\n## Telegram / Discord\n\nBind these profiles to Telegram topics or Discord channels by editing Hermes config after making a backup and running `hermes config check`. Do not restart the gateway until the operator approves.\n\n## Suggested channels/topics\n\n- Scout: research/inbox topic.\n- Librarian: library curation topic.\n- Architect: proposals/recommendations topic.\n- Oracle: private longitudinal-context topic, opt-in only.\n'''

    write(library / 'onboarding' / 'adaptative-config.yaml', config, dry_run=dry_run)
    write(library / 'onboarding' / 'profile-bindings.yaml', bindings, dry_run=dry_run)
    write(library / 'onboarding' / 'BINDING_GUIDE.md', guide, dry_run=dry_run)
    write(library / 'raw' / 'onboarding' / f'initial-discovery-{ts}.md', '\n'.join(raw) + '\n', dry_run=dry_run)

    for role in ROLE_ORDER:
        profile_path = target / 'profiles' / role / 'config.yaml'
        write(profile_path, render_profile(role, provider, models[role], target, args.library_name), dry_run=dry_run)

    if args.obsidian_vault:
        create_obsidian_link(Path(args.obsidian_vault), library, dry_run=dry_run)

    print('onboarding: OK' if not dry_run else 'onboarding dry-run: OK')
    print('side effects: no crons, no gateway restart, no global config edit, no active memory write, no network')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
